#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TN3GMANAGEMENT');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'POLE FORMATION DES INDUSTRIES TECHOLOGIQUES BRETAGNE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'OUAHRANI Mohamed Moncef');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'POLE FORMATION DES INDUSTRIES TECHOLOGIQUES BRETAGNE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Africa Technologiy Relation');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Olivier COLLET');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TRANSPOLE Lille');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'CCIR BURUNDI');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ZEGHOUN Yacine');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where societe = 'EXCEL SUD');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Universit du Burundi');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MANPOWER IT');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Conseil Régional de Guadeloupe');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MAGNA ENIGNEERED GLASS EUROPE');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MAGNA ENIGNEERED GLASS EUROPE');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Departement Seine et Marne');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'PHONE CALL');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SEEE Cote d''ivoire');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TLH');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GPMH');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'UIC');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SCADEC');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ECOLE SUPERIEUR POLYTECHNIQUE DE l''UCAD');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'RODRIGUEZ Roane');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ARCEP BENIN');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Cosmetique Active Production');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'LABEILLE-MARTINEZ');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MOAMMED EL AMINE');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Ministère de la Santé via Patrick Thomas');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'BENSMAIA');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'BGFIGANK GABON');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GOURMAT Karim');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SEGMENTATION');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'FESNEDA John Harry');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ACTIA AUTOMOTIVE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TIENDRESBEOGO Harouna');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'DESIGN PRODUCTION');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SIMAC Tunisie');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MCI');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'DRT');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'BMI');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Mairie de Nogent sur Oise');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Mairie de Nogent sur Oise');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'AYOUB Faggyr');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'VSAMIL Dgga');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'EBWADA MODI');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ch-annecygenevois.fr');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'KOUAWO');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Istifan');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Moulay Mostefa');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Habib');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Varel');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Kemel');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ETUDIAN');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'bogne');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GAVINAUD');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ZEROUKHI');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Delacour ondenault');

