update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GUERIN Manuella'
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'FADHEL Chebil');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'AKISHULI Abdallah');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ECUYER Prescillia');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'LOTZ Christophe');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TN3GMANAGEMENT');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'AKERVA');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'POLE FORMATION DES INDUSTRIES TECHOLOGIQUES BRETAGNE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OUAHRANI Mohamed Moncef');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DATAMED RESEARCH');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'AREA FORMATION');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CONSEIL DEPARTEMENTAL DU CANTAL');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'KINNIOU Hicham');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CCI Normandie');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OLIGOS');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SANOU Abdramane');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'NKECK Nelly');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'POLE FORMATION DES INDUSTRIES TECHOLOGIQUES BRETAGNE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'LE CREUSET SAS');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ZRIG Sadur');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GUEYE Yaye');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DIANE Mouctar');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Africa Technologiy Relation');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MTN Guinea');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SYNALTIC GROUP');

#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SDIS35');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'AW Abdoul Bachir');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'EVOLIS');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'COGNIZANT BUSINESS CONSULTING');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DELTACOM');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ORIANO Jean');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OUZAANI Brahim');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CELIS Laurence');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GS1 FR');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Olivier COLLET');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OPCAIM');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MBA Mutuelle');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DEMBELE Adama');

#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CANON France Business Services');
"update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'IPC GIE');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ETNIC');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MGI Consultants');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Comores Telecom');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Europcar international');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ZELAZKO Patrick');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DJAB Raba');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TRANSPOLE Lille');
update formulaire_contact_detail set potentiel =0  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BENNAI Mohamed Amine');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OPALEDATA');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'NGUYEN DUC Philippe');

#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'EOL SAS');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ADVIDEUM');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'LERICHE Sofian');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'EISTI');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TRADEDOUBLER');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MENAUT Pascal');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CCIR BURUNDI');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ZAOUAGRI Mohamed');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'RAHLI Nourredine');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'VARIAS');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MUKENDE André Fils');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ZEGHOUN Yacine');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'HADJAB Hichem');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'IDRES Mohand');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'EXCEL SUD');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CHU D''ORAN');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'LOUNIS Malek');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SNE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Housing Bank Algérie');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Universit du Burundi');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Nord Picardie Bois');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SOLEDIS');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ELITE AUTO');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'KINAXIA Groupe');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'COULIBALY Mohamed');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'FIBROTECH');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MERABET Djamel');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BETC');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'IDBOUIGUIGUANE Ismael');

#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'POLYGONE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BENADOUDA Mohammed');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Ecole artistique de l''Ubaye');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Objectware');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SOMPO Papy');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MESKINI Zhor Samira');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ALIAS Informatique');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GUIGUE Marc-Edouard');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SOLYSTIC');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MOUKONDO Dunod Bertrand');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'European Patent Office');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Société Internationale de Services');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MBONGA Samuel');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SAGNA Pape');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GEORGET Nicolas');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ROUAMBA Sonia');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GROUPE ORTEC');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Place de la Formation');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'IME BELL''ESTELLO');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'HOME SWEET HOME');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BANQUE NATIONALE DE Belgique');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BINOUS Asma');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MANPOWER IT');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SERMETA');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'RODRIGUEZ Jérôme');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GODARD Alexandre');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'KABA Roi');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Conseil Régional de Guadeloupe');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MAGNA ENIGNEERED GLASS EUROPE');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MAGNA ENIGNEERED GLASS EUROPE');

#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DIAGRAM INFORMATIQUE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DJE Guehi Alain');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CONGO TELECOM');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'APHP');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TOUILEB Lamia');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'INTERFACE RH');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ISSARTIER Patrick');
#update formulaire_contact_detail set potentiel =0  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ALGOFI');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Departement Seine et Marne');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'EDAU Jérôme');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DAVIDSON CONSULTING');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OUZIAD Ahmed');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Centre Hospitalier de Mayotte');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'PHONE CALL');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'RTL');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'PARTITIO');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'FNSEA');
#update formulaire_contact_detail set potentiel =0  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'IMAD');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'FONCIERE DES REGIONS');


#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SEEE Cote d''ivoire');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TLH');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'KIOUA Youcef');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CHAPITEAU Edwin');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GPMH');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'IFONO SAA ISAAC');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TUI France');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'AMILAM FIBRE OPTIQUE');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OPCAIM');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DAOUROU Rolland');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'JOUBARD Philippe');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GIFEKS CONSULTING');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'EPCM SERVICES SPRL');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SPHERE TI');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CHU de Besancon');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GEOXIA Ressources');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GEOXIA Ressources');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BOUCHKOUR Fouad');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'UIC');

#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Service d''Information du Gouvernement');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OO2');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SAIDANA Xavier');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CEPN');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'PCIG');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SCADEC');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'FAUSTIN Melisna');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DEMANOU Renel');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MEDI Hedi');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ECOLE SUPERIEUR POLYTECHNIQUE DE l''UCAD');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'IGN');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ZOUAID Mounir');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DELALAIN Maxime');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'STAUB Fonderie');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MARQUES Corinne');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SERLI');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SERLI');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OPCAIM');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GB and SMITH');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'RT Conseils');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TAN Max');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'NDOUMBE Serge');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OPEN');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'KOUROUMA Consulting');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BEAUGELAS');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MPANDI Prince');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'AXYSWEB');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TURELLE Stéphanie');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'RODRIGUEZ Roane');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'HEMMERSBACH');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ARCEP BENIN');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'HAMI Abdelkadir');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CODIJA Yves');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SAS AUXENS');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'VOLT EUROPE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Cosmetique Active Production');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MARTINO Olivier');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ARTECOMM');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Direction de la Jeunesse Ministere education nationale');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'IT-SS');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TIGF SA');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Human Booster');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'NNE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Energeo Technologies');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Djibouti Telecom');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'LEROUX Mary');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'LABEILLE-MARTINEZ');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MOAMMED EL AMINE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Xenon Private');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MESLIER Alexandra');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Ministère de la Santé via Patrick Thomas');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'RAHMANI Abdelghani');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'KONE Mariane');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'KOUADIO René');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'AKOTIALE Alain');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GAMBIE Sarah');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'EASY BI');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GOBIN Daniel');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'PERO GROUPE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'LAUP Yannick');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TDI');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OXYD');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CAPCO');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BENSMAIA');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'RICOH INDUSTRIE France');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BELAHI Karim');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MISIUK Yannick');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'PRIMACOM');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BGFIGANK GABON');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GOURMAT Karim');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'COULIBALY Mahamadou');

#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'INTERIALE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'COUSSY Alexandre');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BOULAIN Nicolas');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'VITOGAZ France');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TEAM HADY');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SAMMOUD Chadia');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SEGMENTATION');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BENARBIA Yacine');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GUERIDON Olivier');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BENIN ACE GIE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SOGEMI');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MARIONNAUD LAFAYETTE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DIGICEL');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'FESNEDA John Harry');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SEURECA');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GFA Caraibes');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DEGNABINI Robertine');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SEQUOR');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BENIN ACE GIE');

#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ACTIA AUTOMOTIVE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SOM');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MIHINDOU PAGA');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TIENDRESBEOGO Harouna');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MEDJELLEL Ourdia');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'LIDA Josiane');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SIAB Ali');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'KEITA Mamby');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'FLEURY Marcel');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GANDEGA Moussa');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DESIGN PRODUCTION');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SIMAC Tunisie');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'JPM Consulting International');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MOKHFI Boudiaf');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DRAME Khalifa');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MS CONSULTING');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GAYE Samson Martial');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DUBOIS François');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'NAZAIRE Pare');

#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SMS2i');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GMPC');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'EASYRESO');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GAVARIN Kevin');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'KAMARA Aboubakar');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OLSON Pierre Louis');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'PORDEA Irène');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SYSTRA');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MCI');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'haitienne');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'VTB Bank France');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ENSA de Tétouan');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CUQUEMELLE Mélanie');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MINISTERE DE L''INTERIEUR');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Mairie de Calais');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SADOUN Mourad');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BERNI Younes');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MUSKA Engineering SARL');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TOZLU Faith');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'TASK Informatic');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'S2ia');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MBAREK Sondes');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ROCHE Eric');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GROUPE ALLIANCE');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'LETIN Michel');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ACHRAF Farrais');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DRT');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SENTELIS');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'YELLOW');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BOUGOUFFA Mounir');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CNFPT');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DAMIANY Florian');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'KOUASSI Baly');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SECK Franck Thomas');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BMI');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'AFNOR');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ARPCE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MINISTERE DU BUDGET');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'diouf El Hadji Malick');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'OUTAAOUI Mimoun');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'UNIVERSITE PIERRE ET MARIE CURIE');

#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Mairie de Nogent sur Oise');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'KALI Sella');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Mairie de Nogent sur Oise');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CH RAVENEL');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'HOGNON Frédéric');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ELEC CONCEPTION');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BUENSA Mawumba');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'AHARMOUCH Kawthar');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'EXANE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'HONORE Goncalves');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DERSION Melvin');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DAAOU Lyes');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'MOUSTAHIB');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ZEGRANI Yassine');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CAPEL');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'LABGROUP');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'RACHIDI Hadda');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'DIUF EL Hadji Malick');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'COTERM Tunisie');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BMCI');

#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SOUFIANE Akeb Daoud');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'AYOUB Faggyr');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'NGANDU Jean Paul');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'COUPE Damien');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BLUESOFT');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'AXOR SARL');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Jems DataFactory');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'VSAMIL Dgga');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'VISION CRITICAL');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'nlandu mbala chadrack');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'EBWADA MODI');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ch-annecygenevois.fr');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'KOUAWO');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Istifan');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'CSI');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Praxedo');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Moulay Mostefa');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'BMCI');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'siwattag');

#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Monsieur Moulay Mostefa');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'SONATEL');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'La Mutuelle générale');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Habib');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Varel');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Kemel');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ETUDIAN');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Antigua Design');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'bogne');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Gassama');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Pole Medico Sociale Phillippe de CAMARET');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'GAVINAUD');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'ZEROUKHI');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where concat(concat(nom,' '),prenom) = 'Delacour ondenault');

