update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'FADHEL Chebil');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'AKISHULI Abdallah');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TN3GMANAGEMENT');
update formulaire_contact_detail set potentiel =3  where id_formulaire_contact in (select id from formulaire_contact where societe = 'AKERVA');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'POLE FORMATION DES INDUSTRIES TECHOLOGIQUES BRETAGNE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'OUAHRANI Mohamed Moncef');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'DATAMED RESEARCH');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'AREA FORMATION');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'CONSEIL DEPARTEMENTAL DU CANTAL');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'CCI Normandie');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'OLIGOS');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'POLE FORMATION DES INDUSTRIES TECHOLOGIQUES BRETAGNE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'LE CREUSET SAS');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Africa Technologiy Relation');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'MTN Guinea');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SYNALTIC GROUP');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'SDIS35');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'EVOLIS');
update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where societe = 'COGNIZANT BUSINESS CONSULTING');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'DELTACOM');
update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GS1 FR');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Olivier COLLET');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'OPCAIM');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MBA Mutuelle');

update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'CANON France Business Services');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'IPC GIE');
update formulaire_contact_detail set potentiel =3  where id_formulaire_contact in (select id from formulaire_contact where societe = 'ETNIC');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MGI Consultants');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'Comores Telecom');
update formulaire_contact_detail set potentiel =3  where id_formulaire_contact in (select id from formulaire_contact where societe = 'Europcar international');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TRANSPOLE Lille');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'OPALEDATA');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'NGUYEN DUC Philippe');

update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where societe = 'EOL SAS');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ADVIDEUM');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'EISTI');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TRADEDOUBLER');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'CCIR BURUNDI');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ZAOUAGRI Mohamed');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'VARIAS');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MUKENDE André Fils');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ZEGHOUN Yacine');
#update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where societe = 'EXCEL SUD');
update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where societe = 'CHU D''ORAN');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'SNE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'Housing Bank Algérie');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Universit du Burundi');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Nord Picardie Bois');
update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SOLEDIS');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ELITE AUTO');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'KINAXIA Groupe');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'FIBROTECH');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'BETC');

update formulaire_contact_detail set potentiel =3  where id_formulaire_contact in (select id from formulaire_contact where societe = 'POLYGONE');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Ecole artistique de l''Ubaye');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'Objectware');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ALIAS Informatique');
update formulaire_contact_detail set potentiel =3  where id_formulaire_contact in (select id from formulaire_contact where societe = 'SOLYSTIC');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'European Patent Office');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Société Internationale de Services');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ROUAMBA Sonia');
update formulaire_contact_detail set potentiel =3  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GROUPE ORTEC');
update formulaire_contact_detail set potentiel =3  where id_formulaire_contact in (select id from formulaire_contact where societe = 'Place de la Formation');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'IME BELL''ESTELLO');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'HOME SWEET HOME');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'BANQUE NATIONALE DE Belgique');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MANPOWER IT');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SERMETA');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Conseil Régional de Guadeloupe');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MAGNA ENIGNEERED GLASS EUROPE');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MAGNA ENIGNEERED GLASS EUROPE');

update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'DIAGRAM INFORMATIQUE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'DJE Guehi Alain');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'CONGO TELECOM');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'APHP');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'INTERFACE RH');
update formulaire_contact_detail set potentiel =0  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ALGOFI');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Departement Seine et Marne');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'DAVIDSON CONSULTING');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'OUZIAD Ahmed');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'Centre Hospitalier de Mayotte');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'PHONE CALL');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'RTL');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'PARTITIO');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'FNSEA');
update formulaire_contact_detail set potentiel =0  where id_formulaire_contact = (select id from formulaire_contact where societe = 'IMAD');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'FONCIERE DES REGIONS');


#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SEEE Cote d''ivoire');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TLH');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GPMH');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'IFONO SAA ISAAC');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TUI France');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'AMILAM FIBRE OPTIQUE');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'OPCAIM');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GIFEKS CONSULTING');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'EPCM SERVICES SPRL');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SPHERE TI');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'CHU de Besancon');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'GEOXIA Ressources');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GEOXIA Ressources');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'UIC');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Service d''Information du Gouvernement');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'OO2');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'CEPN');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'PCIG');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SCADEC');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ECOLE SUPERIEUR POLYTECHNIQUE DE l''UCAD');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'IGN');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'STAUB Fonderie');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'SERLI');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SERLI');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'OPCAIM');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GB and SMITH');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'RT Conseils');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'OPEN');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'KOUROUMA Consulting');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'AXYSWEB');

#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'RODRIGUEZ Roane');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'HEMMERSBACH');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ARCEP BENIN');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'CODIJA Yves');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SAS AUXENS');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'VOLT EUROPE');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Cosmetique Active Production');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ARTECOMM');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Direction de la Jeunesse Ministere education nationale');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'IT-SS');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TIGF SA');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'Human Booster');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'NNE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Energeo Technologies');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'Djibouti Telecom');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'LABEILLE-MARTINEZ');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MOAMMED EL AMINE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Xenon Private');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Ministère de la Santé via Patrick Thomas');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'EASY BI');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'PERO GROUPE');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'TDI');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'OXYD');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'CAPCO');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'BENSMAIA');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'RICOH INDUSTRIE France');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'PRIMACOM');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'BGFIGANK GABON');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GOURMAT Karim');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'INTERIALE');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'VITOGAZ France');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TEAM HADY');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SEGMENTATION');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GUERIDON Olivier');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'BENIN ACE GIE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SOGEMI');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MARIONNAUD LAFAYETTE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'DIGICEL');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'FESNEDA John Harry');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SEURECA');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GFA Caraibes');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'DEGNABINI Robertine');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SEQUOR');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'BENIN ACE GIE');

#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ACTIA AUTOMOTIVE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'SOM');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MIHINDOU PAGA');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TIENDRESBEOGO Harouna');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MEDJELLEL Ourdia');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'DESIGN PRODUCTION');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SIMAC Tunisie');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'JPM Consulting International');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MS CONSULTING');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SMS2i');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GMPC');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'EASYRESO');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GAVARIN Kevin');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'OLSON Pierre Louis');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SYSTRA');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MCI');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'haitienne');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'VTB Bank France');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ENSA de Tétouan');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'MINISTERE DE L''INTERIEUR');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Mairie de Calais');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MUSKA Engineering SARL');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'TOZLU Faith');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'TASK Informatic');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'S2ia');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'MBAREK Sondes');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'GROUPE ALLIANCE');

#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'DRT');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SENTELIS');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'YELLOW');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'CNFPT');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'BMI');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'AFNOR');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'ARPCE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'MINISTERE DU BUDGET');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'UNIVERSITE PIERRE ET MARIE CURIE');

#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Mairie de Nogent sur Oise');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Mairie de Nogent sur Oise');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'CH RAVENEL');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ELEC CONCEPTION');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'EXANE');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'CAPEL');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'LABGROUP');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'DIUF EL Hadji Malick');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'COTERM Tunisie');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'BMCI');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'SOUFIANE Akeb Daoud');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'AYOUB Faggyr');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'NGANDU Jean Paul');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'COUPE Damien');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'BLUESOFT');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'AXOR SARL');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Jems DataFactory');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'VSAMIL Dgga');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'VISION CRITICAL');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'EBWADA MODI');
#update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ch-annecygenevois.fr');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'KOUAWO');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Istifan');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'CSI');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Praxedo');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Moulay Mostefa');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'BMCI');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'siwattag');

update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Monsieur Moulay Mostefa');
update formulaire_contact_detail set potentiel =3  where id_formulaire_contact in (select id from formulaire_contact where societe = 'SONATEL');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact in (select id from formulaire_contact where societe = 'La Mutuelle générale');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Habib');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Varel');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Kemel');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ETUDIAN');
update formulaire_contact_detail set potentiel =1  where id_formulaire_contact in (select id from formulaire_contact where societe = 'Antigua Design');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'bogne');
update formulaire_contact_detail set potentiel =2  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Pole Medico Sociale Phillippe de CAMARET');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'GAVINAUD');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'ZEROUKHI');
#update formulaire_contact_detail set potentiel =1  where id_formulaire_contact = (select id from formulaire_contact where societe = 'Delacour ondenault');

