delete from partenaire;
insert into partenaire  (id,nom) values (1,'First Group');
insert into partenaire  (id,nom) values (2,'Infhotep');
insert into partenaire  (id,nom) values (3,'Logica');
insert into partenaire  (id,nom) values (4,'IEF2I');
insert into partenaire  (id,nom) values (5,'Alterway');
insert into partenaire  (id,nom) values (6,'Learneo');
insert into partenaire  (id,nom) values (7,'Oxiane');
insert into partenaire  (id,nom) values (8,'Ziggourat');
insert into partenaire  (id,nom) values (9,'Micropole Institut');
insert into partenaire  (id,nom) values (10,'Akteos');
insert into partenaire  (id,nom) values (11,'capitecorpus');
insert into partenaire  (id,nom) values (12,'Allyans');
insert into partenaire  (id,nom) values (13,'HSC');
insert into partenaire  (id,nom) values (14,'Byward');
insert into partenaire  (id,nom) values (15,'MATRICS');
insert into partenaire  (id,nom) values (16,'oratech');
insert into partenaire  (id,nom) values (17,'LTI');
insert into partenaire  (id,nom) values (18,'IBM');
insert into partenaire  (id,nom) values (19,'IGTECH');
insert into partenaire  (id,nom) values (20,'LFI');
insert into partenaire  (id,nom) values (21,'bcf');
insert into partenaire  (id,nom) values (22,'zenika');
insert into partenaire  (id,nom) values (23,'M2I');
insert into partenaire  (id,nom) values (24,'ORSYP');
insert into partenaire  (id,nom) values (25,'Dalibo');
insert into partenaire  (id,nom) values (26,'Ambre systems');
insert into partenaire  (id,nom) values (27,'Sekoia');
insert into partenaire  (id,nom) values (28,'SYSDREAM');
insert into partenaire  (id,nom) values (29,'BULL');
insert into partenaire  (id,nom) values (30,'GKN');
insert into partenaire  (id,nom) values (31,'IB');
insert into partenaire  (id,nom) values (32,'Orsys');
insert into partenaire  (id,nom) values (33,'Pythagore');
insert into partenaire  (id,nom) values (34,'EDU');
insert into partenaire  (id,nom) values (35,'Edugroupe');
insert into partenaire  (id,nom) values (36,'Winwise');
insert into partenaire  (id,nom) values (37,'Adeneo');
insert into partenaire  (id,nom) values (38,'Objis');